FROM node:20-slim

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Espone la porta corretta di Vite
EXPOSE 5173

# Avvia Vite forzando l'ascolto su tutte le interfacce di rete (0.0.0.0)
CMD ["npm", "run", "dev", "--", "--host"]
